### ISSUE TITLE
Docker container build issues

### ISSUE THREAD

**Issue by LukeCarrier** [LukeCarrier/moodle-ubiquitous#11]
We stopped paying attention to Docker for a while and the huge number of changes to the states seems to have broken things a little. Let's fix that. 

- [x] Locales
- [x] `msodbcsql` installation and `ACCEPT_EULA`
- [x] `chromedriver` state

# Locales

```
[ERROR   ] [Errno 2] No such file or directory: '/usr/share/i18n/locales'
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1746, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1704, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/locale.py", line 92, in present
    if __salt__['locale.gen_locale'](name):
  File "/usr/lib/python2.7/dist-packages/salt/modules/localemod.py", line 293, in gen_locale
    "Locale \"{0}\" is not available.".format(locale))
CommandExecutionError: Locale "en_AU.UTF-8" is not available.

[ERROR   ] [Errno 2] No such file or directory: '/usr/share/i18n/locales'
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1746, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1704, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/locale.py", line 92, in present
    if __salt__['locale.gen_locale'](name):
  File "/usr/lib/python2.7/dist-packages/salt/modules/localemod.py", line 293, in gen_locale
    "Locale \"{0}\" is not available.".format(locale))
CommandExecutionError: Locale "en_GB.UTF-8" is not available.

[ERROR   ] [Errno 2] No such file or directory: '/usr/share/i18n/locales'
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1746, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1704, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/locale.py", line 92, in present
    if __salt__['locale.gen_locale'](name):
  File "/usr/lib/python2.7/dist-packages/salt/modules/localemod.py", line 293, in gen_locale
    "Locale \"{0}\" is not available.".format(locale))
CommandExecutionError: Locale "en_US.UTF-8" is not available.
```
# `msodbcsql` and `ACCEPT_EULA`

```
[ERROR   ] Command '['apt-get', '-q', '-y', '-o', 'DPkg::Options::=--force-confold', '-o', 'DPkg::Options::=--force-confdef', 'install', 'msodbcsql', 'unixodbc-dev']' failed with return code: 100
```

# `chromedriver` state

```
[WARNING ] State for file: /opt/selenium/chromedriver/chromedriver - Neither 'source' nor 'contents' nor 'contents_pillar' nor 'contents_grains' was defined, yet 'replace' was set to 'True'. As there is no source to replace the file with, 'replace' has been set to 'False' to avoid reading the file unnecessarily.
```

**Comment by LukeCarrier** [comment]
Fixed as of b0dc3f6ff7c0982a9c02fe6820d022e6b4817cbc
